# Generated by Django 5.0.6 on 2026-09-16 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('combined_video', 'Combined face and spoken statement video'), ('phonation_audio', 'Voice phonation audio')], max_length=40)),
                ('file', models.FileField(upload_to='captures/%Y/%m/%d/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_captures', to='collection.collectionsession')),
            ],
        ),
    ]
