# Generated by Django 5.0.6 on 2026-09-16 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_mediacapture'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionsession',
            name='current_step',
            field=models.CharField(default='questionnaire', max_length=40),
        ),
        migrations.AddField(
            model_name='collectionsession',
            name='status',
            field=models.CharField(choices=[('questionnaire', 'Questionnaire'), ('capture', 'Capture'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='questionnaire', max_length=20),
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('face', 'Face'), ('text', 'Text'), ('voice', 'Voice'), ('multimodal', 'Multimodal')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transcript', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('normalized_result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_results', to='collection.mediacapture')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='collection.collectionsession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'modality'], name='collection__session_a6f5ec_idx'), models.Index(fields=['status'], name='collection__status_b0a720_idx')],
            },
        ),
    ]
