# Generated by Django 6.0.8 on 2026-09-22 09:00

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0003_collectionsession_current_step_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediacapture",
            name="file",
            field=models.FileField(upload_to=collection.models.media_capture_upload_path),
        ),
    ]
