# Generated by Django 5.1.15 on 2026-09-24 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_mediacapture_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsession',
            name='current_step',
            field=models.CharField(default='consent', max_length=40),
        ),
        migrations.AlterField(
            model_name='collectionsession',
            name='status',
            field=models.CharField(choices=[('consent', 'Consent'), ('questionnaire', 'Questionnaire'), ('capture', 'Capture'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='consent', max_length=20),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('consent_record_date', models.DateField()),
                ('agree_voice', models.BooleanField(default=False)),
                ('agree_video', models.BooleanField(default=False)),
                ('agree_transcript', models.BooleanField(default=False)),
                ('agree_publication', models.BooleanField(default=False)),
                ('agree_terms', models.BooleanField(default=False)),
                ('is_minor', models.BooleanField(default=False)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_relationship', models.CharField(blank=True, max_length=100)),
                ('guardian_contact', models.CharField(blank=True, max_length=100)),
                ('guardian_confirm_parent', models.BooleanField(default=False)),
                ('guardian_confirm_minor', models.BooleanField(default=False)),
                ('guardian_confirm_modalities', models.BooleanField(default=False)),
                ('guardian_confirm_terms', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='collection.collectionsession')),
            ],
        ),
    ]
