# Generated by Django 5.1.15 on 2026-09-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_alter_collectionsession_current_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentrecord',
            name='participant_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
